export const contentStrings = [
  "Scotland has over 790 offshore islands",
  "Edinburgh Castle is built on an extinct volcano",
  "The unicorn is Scotland's national animal",
  "The world's first color photograph was taken in Scotland",
  "Scotland's national drink, Irn-Bru, outsells Coca-Cola",
  "Golf was invented in Scotland in the 15th century",
  "Loch Ness holds more freshwater than all English and Welsh lakes combined",
  "Bagpipes were not originally invented in Scotland",
  "Edinburgh was the first city in the world to have its own fire brigade",
  "Scotland has three officially recognized languages",
  "The raincoat (mackintosh) was invented by a Scot",
  "Scotland has over 30,000 lochs",
  "There are more Scots living abroad than in Scotland",
  "The longest echo in the world was recorded in a Scottish cavern",
  "The world's first cloned mammal, Dolly the Sheep, was created in Scotland",
  "Ben Nevis is the highest mountain in the UK",
  "Scotch whisky must be aged at least 3 years to be called Scotch",
  "St Andrews is the oldest university in Scotland, founded in 1413",
  "The Harry Potter Hogwarts Express scenes were filmed in Scotland",
  "Edinburgh hosts the world's largest arts festival, the Fringe",
  "Scotland has its own version of Stonehenge, called Callanish Stones",
  "Haggis is Scotland's national dish",
  "Scotland's national flower is the thistle",
  "The modern raincoat was invented by Charles Macintosh, a Scot",
  "The adhesive postage stamp was invented by a Scot",
  "Pink Floyd's iconic prism logo was created by a Scottish designer",
  "There are more sheep than people on the Isle of Skye",
  "Gaelic was once the dominant language across Scotland",
  "Scotland's flag, the Saltire, is one of the oldest national flags in the world",
  "The game of curling originated in Scotland",
  "Scotland has its own banknotes, accepted across the UK",
  "The world's first teaching hospital was founded in Edinburgh",
  "Edinburgh's Old Town has an underground city known as Mary King's Close",
  "Macbeth, King of Scotland, inspired Shakespeare's tragedy",
  "The deep-fried Mars Bar was invented in Scotland",
  "Shetland ponies originate from the Shetland Islands",
  "Scotland has more than 2,000 castles",
  "The first successful steamship was built by a Scot",
  "Saint Andrew is the patron saint of Scotland",
  "Scotland is home to the UK's oldest tree, the Fortingall Yew",
  "The Highland Games inspired modern Olympic events",
  "Scotland introduced the first modern police force",
  "Glasgow was once the world's largest shipbuilding center",
  "Inverness is often called the capital of the Highlands",
  "The national motto of Scotland is 'In My Defens God Me Defend'",
  "The Scots invented the telephone (Alexander Graham Bell)",
  "The oldest lighthouse still in operation is in Scotland",
  "Halloween traditions like guising originated in Scotland",
  "The famous monster of Loch Ness was first reported in the 6th century",
];
